nba:
    dataset: 'nba'
    nclass: 3
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 20000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'batch'
    sens_attr: 'country'
    predict_attr: 'SALARY'
    path: 'data/ori/nba/'
    label_number: 200
    k_start: 100
    k_end: 200
    k_jump: 100
    sens_idex: False
pokec_z:
    dataset: 'region_job'
    nclass: 5
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 20000
    lr: 0.001
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    sens_attr: 'region'
    predict_attr: 'I_am_working_in_field'
    path: 'data/ori/pokec/'
    label_number: 1000
    k_start: 100
    k_end: 200
    k_jump: 100
    sens_idex: False
pokec_n:
    dataset: 'region_job_2'
    nclass: 6
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 20000
    lr: 0.01
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    sens_attr: 'region'
    predict_attr: 'I_am_working_in_field'
    path: 'data/ori/pokec/'
    label_number: 1000
    k_start: 1000
    k_end: 1100
    k_jump: 100
    sens_idex: False

credit:
    dataset: 'credit'
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 20000
    lr: 0.01
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    sens_attr: 'Age'
    predict_attr: 'NoDefaultNextMonth'
    path: 'data/ori/credit/'
    label_number: 1000
    k_start: 100
    k_end: 200
    k_jump: 100
    sens_idex: False

income:
    dataset: 'income'
    nclass: 2
    nlayer: 1
    num_heads: 1
    hidden_dim: 128
    epoch: 20000
    lr: 0.01
    weight_decay: 0.00001
    tran_dropout: 0.5
    feat_dropout: 0.5
    prop_dropout: 0.5
    norm: 'layer'
    sens_attr: 'race'
    predict_attr: 'income'
    path: 'data/ori/income/'
    label_number: 1000
    k_start: 3000
    k_end: 3100
    k_jump: 100
    sens_idex: False